# Generated by Django 5.2.8 on 2025-11-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_admin', True)), fields=('is_admin',), name='only_one_admin_role'),
        ),
    ]
