# Generated by Django 5.2.8 on 2025-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='jti',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
