# Generated by Django 5.2.8 on 2025-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_remove_refreshtoken_token_refreshtoken_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='jti',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
